### ISSUE TITLE
Use sqlite in ios APP

### ISSUE THREAD

**Issue by encero** [encero/reciper#59]
We should try to do POC for syncing local sqlite mirror of server data. It will be more user friendly. 

### Tasks

- [ ] determine feasibility with current gql queries/mutations
- [ ] store entity verision in api and provide this value in gql
- [ ] devise a way to quickly check if the app is in sync
- [ ] implement poc in ios APP
