### ISSUE TITLE
iOS: sort by last cooked

### ISSUE THREAD

**Issue by encero** [encero/reciper#62]
It's useful to sort recipes by last cooked date. 

### Tasks
- [ ] API: keep track of last cooked date
- [ ] GQL: expose the date
- [ ] iOS: use the data from gql and write sorting
